### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by hy9be** [kennymuse/UIAlertView#1]
Hi I need to clean up a lot UIAlertView deprecation in an app, and your wrapper looks promising as it aimed at transparency. Could you tell how should I use it? Add all files in the ``UIAlertViewWrapper`` folder, and do not change anything else?

Thanks!

**Comment by kennymuse** [comment]
Hi, import the classes in the Xcode project; then in the pch of the project or in every view controller write #import "UIAlertView+Extension.h".

**Comment by hy9be** [comment]
Thanks for the reply!

I followed your steps but still got the deprecation warning:
![image](https://cloud.githubusercontent.com/assets/3392907/25585489/c1a66f30-2e68-11e7-8757-f3d70060a355.png)

Any directions for further investigation?

**Comment by kennymuse** [comment]
The warning is normal. The AlertView is deprecated (with my solution you don't use UIAlertView with new iOS >= 9 but the warning exist). If you want you can force XCode to hide the warning. Search with google. ;-)

**Comment by hy9be** [comment]
Got it. Thanks!

**Comment by kennymuse** [comment]
The utility of these classes is in UIAlertView's massive replacement with UIAlertController. I had to replace them on a very large project (many UIAlertViews) because there were unexpected graphic effects (flickering, etc.). The warnings remain but they can be hidden forcibly.
